[service]
port = 44448

[event_store]
host = "0.0.0.0:32803"
cluster_id = "test-cluster"

[rules]
ruleconfig = "./rules/rules.json"
dbconfig = "./rules/database.json"
exporterconfig = "./rules/exporter.json"
