[service]
port = 44448

[event_store]
host = "0.0.0.0:32803"
cluster_id = "test-cluster"
client_name = "synchronizeri-1"
durable_name = "synchronizeri-1"

[cache_store]
host = "0.0.0.0:44446"

[rules]
dbconfig = "./rules/database.json"
exporterconfig = "./rules/exporter.json"
storeconfig = "./rules/store.json"
triggerconfig = "./rules/trigger.json"

[state_store]
path = "./state"
