[gravity]
domain = "gravity"
accessKey = "TestingACCESSkey"
host = "0.0.0.0"
port = 32803
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1

[dsa]
workerCount = 4

[pipeline]
pipelineCount = 4
workerCount = 16
workerBufferSize = 102400

[snapshot]
workerCount = 8
workerBufferSize = 102400

[datastore]
path = "./datastore"

[rules]
store = "./rules/store.json"
